apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back-git
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back-git
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front-git
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front-git
